{% set name = "torchtitan" %}
{% set version = "0.2.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/torchtitan-{{ version }}.tar.gz
  sha256: 0b288bd9eb3d775f20ba00d9d71449023c8b224e356fa46744b94aa863217ca8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - blobfile
    - datasets >=3.6.0
    - einops
    - fsspec
    - pillow
    - python >={{ python_min }}
    - pytorch >=2.3.1
    - sentencepiece
    - tensorboard
    - tiktoken
    - tomli >=1.1.0
    - tokenizers >=0.15.0
    - torchdata >=0.8.0
    - transformers
    - triton
    - tyro
    - tabulate
    - wandb

test:
  # imports:
  #   - torchtitan
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pytorch/torchtitan
  summary: A PyTorch native platform for training generative AI models
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
